name: Verify README examples, release to PyPI
on:
  push:
    branches: [ "main" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  test:
    name: Verify README examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python 3.11
        run: uv python install 3.11
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install parquet2json
      - name: Install dependencies
        run: uv sync --extra ci --extra test
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest
      - name: '`dvc pull` test/data'
        working-directory: test/data
        run: |
          source ../../.venv/bin/activate
          dvc pull -r s3 -R -A
      - name: Set up parquet-helpers
        uses: actions/checkout@v4
        with:
          repository: ryan-williams/parquet-helpers
          path: pqt
      - name: Verify README examples
        env:
          # Evaluate README examples from within the `test/data` submodule
          BMDF_WORKDIR: test/data
        run: |
          source .venv/bin/activate
          export PATH="$PWD/pqt:$PATH"
          . pqt/.pqt-rc
          export SHELL
          mdcmd
          git diff --exit-code
  release:
    name: Release to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uv build
      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            --generate-notes
