name: Release to PyPI
on:
  push:
#    branches: [ "main" ]
    tags: [ "v**" ]
#  pull_request:
#    branches:
#      - "**"
jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install release deps
        run: pip install utz[setup] twine wheel
      - name: Install dvc-utils
        run: pip install -e .
      - name: Build release
        run: python setup.py sdist bdist_wheel
      - name: Publish release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*
